src/Entity/Voyage.php
<?php

namespace App\Entity;

use App\Repository\VoyageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoyageRepository::class)]
class Voyage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $image_path = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(length: 255)]
    private ?string $detailed_description = null;

    #[ORM\Column(length: 255)]
    private ?string $destination = null;

    #[ORM\Column(length: 255)]
    private ?string $duration = null;

    #[ORM\Column(length: 255)]
    private ?string $start_time = null;

    #[ORM\ManyToMany(targetEntity: User::class)]
    private Collection $user;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(string $image_path): static
    {
        $this->image_path = $image_path;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDetailedDescription(): ?string
    {
        return $this->detailed_description;
    }

    public function setDetailedDescription(string $detailed_description): static
    {
        $this->detailed_description = $detailed_description;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): static
    {
        $this->destination = $destination;

        return $this;
    }

    public function getDuration(): ?string
    {
        return $this->duration;
    }

    public function setDuration(string $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getStartTime(): ?string
    {
        return $this->start_time;
    }

    public function setStartTime(string $start_time): static
    {
        $this->start_time = $start_time;

        return $this;
    }

    /**
     * @return Collection<int, user>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(user $user): static
    {
        if (!$this->user->contains($user)) {
            $this->user->add($user);
        }

        return $this;
    }

    public function removeUser(user $user): static
    {
        $this->user->removeElement($user);

        return $this;
    }
}

src/Controller/VoyageController.php
<?php

namespace App\Controller;

use App\Entity\Voyage;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/voyage', name: 'app_voyage_')]
class VoyageController extends AbstractController
{
    #[Route('/{id}', name: 'details')]
    public function voyage(Voyage $voyage): Response
    {

        return $this->render('voyage/details.html.twig', [
            'voyage' => $voyage
        ]);
    }


    // #[Route('/voyage/{id}', 'voyage.show')]
    // public function show(
    //     Voyage $voyage,
    //     Request $request,
        
    // ) : Response{
    //     // new Voyage();


    //     return $this->render('voyage/details.html.twig', [
    //        'voyage' => $voyage 
    //     ]);

    // }

}

templates/voyage/details.html.twig
{% extends 'base.html.twig' %}
 
{% block body %}
{# <div class="mt-4"> {{voyage.getImagePath}}</div>
<div class="mt-4"> {{voyage.description}}</div>
<div class="mt-4">Prix du voyage {{voyage.price}}</div>
<div class="mt-4"> {{voyage.getDetailedDescription}}</div>
<div class="mt-4"> {{voyage.destination}}</div>
<div class="mt-4">Le voyage dure  {{voyage.duration}}</div>
<div class="mt-4">Le voyage commence le {{voyage.getStartTime}}</div> #}

 <div id="{{ voyage.destination }}" class="d-flex justify-content-center flex-column">
          <div class="card" style="width: 100%; height: auto;">
            <img src="{{asset('assets/images/') ~ voyage.imagePath}}" class="imageCard" alt="image destination" style="height: auto;">
            <div class="card-body">
              <h5 class="card-title text-center">{{voyage.destination}}</h5>
              <p class="card-text">{{voyage.description}}</p>
              <p class="card-text">{{voyage.duration}}</p>
              <p class="card-text">{{voyage.detailedDescription}}</p>

              <div class="d-flex justify-content-center">
              <a href="{{ path('app_voyage_details', {id: voyage.id}) }}" class="btn btn-info">{{voyage.price}} €</a>
              </div>
            </div>

{% endblock %}

templates/voyage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VoyageController!{% endblock %}

{% block body %}
 {% for voyage in voyage %}
 <a href="{{path('')}}" class="btn-primary">Voir les détails</a>
 {% endfor %}
{% endblock %}